<?php

namespace App\Http\Livewire\Page\Siskop\Finance;

use App\Models\AccountMaster;
use App\Models\AccountStatus;
use Livewire\Component;

class Master extends Component
{
    public $uuid, $payment_term, $account;
    
    public function render()
    {
        $this->payment_term = 'm';
        if($this->uuid == 1){
            $this->account = [
                'actid'	=>	'166826',
                'account_no'	=>	'1001026199',
                'product_code'	=>	'10',
                'product_sub_code'	=>	'1',
                'branch_code'	=>	NULL,
                'facility_type'	=>	'34391',
                'funding_scheme'	=>	'0',
                'purpose_code'	=>	'9000',
                'concept'	=>	'26',
                'cif_system'	=>	'A11',
                'report_date'	=>	NULL,
                'payment_term'	=>	'M',
                'approved_currency'	=>	'MYR',
                'approved_limit'	=>	'10000',
                'purchase_price'	=>	'10000',
                'selling_price'	=>	'15750',
                'duration'	=>	'120',
                'profit_rate'	=>	'5.75',
                'instal_amount'	=>	'131.25',
                'fees_amount'	=>	'0',
                'approved_date'	=>	'2020-09-03',
                'opened_date'	=>	'2020-09-08',
                'start_disbursed_date'	=>	'2021-04-10',
                'disbursement_type'	=>	'1',
                'start_instal_date'	=>	'2021-05-30',
                'instal_type'	=>	NULL,
                'total_instal_amt'	=>	'131.25',
                'account_status'	=>	'0',
                'acct_stat_chg_date'	=>	NULL,
                'orig_tenure'	=>	'120',
                'reschedule_flag'	=>	NULL,
                'legal_action_status'	=>	NULL,
                'legal_status_date'	=>	NULL,
                'review_date'	=>	NULL,
                'next_review_date'	=>	NULL,
                'review_freq'	=>	NULL,
                'review_notes'	=>	NULL,
                'last_review_date'	=>	NULL,
                'reminder_flag'	=>	NULL,
                'no_of_reminders'	=>	NULL,
                'next_reminder_date'	=>	NULL,
                'last_reminder_date'	=>	NULL,
                'early_settle_date'	=>	NULL,
                'rebate_amt'	=>	NULL,
                'settle_amt'	=>	NULL,
                'eff_settle_date'	=>	NULL,
                'early_settle_notice_date'	=>	NULL,
                'date_of_settle'	=>	NULL,
                'instal_mode'	=>	NULL,
                'multitier_flag'	=>	NULL,
                'accrual_flag'	=>	NULL,
                'accept_sign_date'	=>	NULL,
                'accept_sign_expire'	=>	NULL,
                'account_officer'	=>	NULL,
                'processing_officer'	=>	NULL,
                'approval_code'	=>	NULL,
                'create_date'	=>	NULL,
                'closed_date'	=>	'2031-04-30',
                'verified_status'	=>	NULL,
                'verified_date'	=>	NULL,
                'mbr_id'	=>	'4642',
                'bnm_code'	=>	NULL,
                'bnm_scc'	=>	NULL,
                'monthly_fees'	=>	'0',
                'monthly_bpa'	=>	'0',
                'batch_bsas'	=>	NULL,
                'sijil_bsas'	=>	NULL,
                'batch_bsas_date'	=>	NULL,
                'sijil_date'	=>	NULL,
                'address_p'	=>	NULL,
                'lot_no_p'	=>	NULL,
                'no_hak_p'	=>	NULL,
                'area_p'	=>	NULL,
                'gtr1'	=>	NULL,
                'gtr2'	=>	NULL,
                'loanno'	=>	NULL,
                'remarks'	=>	NULL,
                'insurance_con_amt'	=>	NULL,
                'insurance_policy_no'	=>	NULL,
                'insurance_policy_date'	=>	NULL,
                'insurance_comm_date'	=>	NULL,
                'last_modified_user'	=>	'faisol',
                'last_modified_date'	=>	'2021-04-09',
                'checker_last_users'	=>	'faisol',
                'checker_last_update'	=>	'2021-04-21',
            ];
        }else{
            $this->account = [
                'actid'	=>	'176828',
                'account_no'	=>	'1001026203',
                'product_code'	=>	'10',
                'product_sub_code'	=>	'1',
                'branch_code'	=>	NULL,
                'facility_type'	=>	'34391',
                'funding_scheme'	=>	'0',
                'purpose_code'	=>	'9000',
                'concept'	=>	'26',
                'cif_system'	=>	'A11',
                'report_date'	=>	NULL,
                'payment_term'	=>	'M',
                'approved_currency'	=>	'MYR',
                'approved_limit'	=>	'88000',
                'purchase_price'	=>	'88000',
                'selling_price'	=>	'112578.4',
                'duration'	=>	'84',
                'profit_rate'	=>	'3.99',
                'instal_amount'	=>	'1340.22',
                'fees_amount'	=>	'0',
                'approved_date'	=>	'2021-04-07',
                'opened_date'	=>	'2021-04-09',
                'start_disbursed_date'	=>	'2021-04-09',
                'disbursement_type'	=>	NULL,
                'start_instal_date'	=>	'2021-04-09',
                'instal_type'	=>	NULL,
                'total_instal_amt'	=>	'1340.22',
                'account_status'	=>	'0',
                'acct_stat_chg_date'	=>	NULL,
                'orig_tenure'	=>	'84',
                'reschedule_flag'	=>	NULL,
                'legal_action_status'	=>	NULL,
                'legal_status_date'	=>	NULL,
                'review_date'	=>	NULL,
                'next_review_date'	=>	NULL,
                'review_freq'	=>	NULL,
                'review_notes'	=>	NULL,
                'last_review_date'	=>	NULL,
                'reminder_flag'	=>	NULL,
                'no_of_reminders'	=>	NULL,
                'next_reminder_date'	=>	NULL,
                'last_reminder_date'	=>	NULL,
                'early_settle_date'	=>	NULL,
                'rebate_amt'	=>	NULL,
                'settle_amt'	=>	NULL,
                'eff_settle_date'	=>	NULL,
                'early_settle_notice_date'	=>	NULL,
                'date_of_settle'	=>	NULL,
                'instal_mode'	=>	NULL,
                'multitier_flag'	=>	NULL,
                'accrual_flag'	=>	NULL,
                'accept_sign_date'	=>	NULL,
                'accept_sign_expire'	=>	NULL,
                'account_officer'	=>	NULL,
                'processing_officer'	=>	NULL,
                'approval_code'	=>	NULL,
                'create_date'	=>	NULL,
                'closed_date'	=>	NULL,
                'verified_status'	=>	NULL,
                'verified_date'	=>	NULL,
                'mbr_id'	=>	'4642',
                'bnm_code'	=>	NULL,
                'bnm_scc'	=>	NULL,
                'monthly_fees'	=>	'0',
                'monthly_bpa'	=>	'0',
                'batch_bsas'	=>	NULL,
                'sijil_bsas'	=>	NULL,
                'batch_bsas_date'	=>	NULL,
                'sijil_date'	=>	NULL,
                'address_p'	=>	NULL,
                'lot_no_p'	=>	NULL,
                'no_hak_p'	=>	NULL,
                'area_p'	=>	NULL,
                'gtr1'	=>	NULL,
                'gtr2'	=>	NULL,
                'loanno'	=>	NULL,
                'remarks'	=>	NULL,
                'insurance_con_amt'	=>	NULL,
                'insurance_policy_no'	=>	NULL,
                'insurance_policy_date'	=>	NULL,
                'insurance_comm_date'	=>	NULL,
                'last_modified_user'	=>	'dbo',
                'last_modified_date'	=>	'2021-04-09',
                'checker_last_users'	=>	NULL,
                'checker_last_update'	=>	NULL,
            ];
        }

        return view('livewire.page.siskop.finance.master',[
        ]);
    }
}
