<?php

namespace App\Http\Livewire\Page\Siskop\Finance;

use App\Models\AccountMaster;
use App\Models\AccountPosition;
use Livewire\Component;

class Position extends Component
{
    public $uuid, $account_position;
    public function render()
    {
        if($this->uuid == 1){
            $this->account_position = [
                'actid'	=>	'159292',
                'account_no'	=>	'1001026199',
                'report_date'	=>	'2021-06-09',
                'cif_system'	=>	'A11',
                'undrawn_amount'	=>	'0.00',
                'disbursed_amount'	=>	'10000.00',
                'bal_outstanding'	=>	'15487.50',
                'cost_outstanding'	=>	'9833.34',
                'prin_outstanding'	=>	'9833.34',
                'uei_outstanding'	=>	'5654.16',
                'total_fees_amount'	=>	NULL,
                'tot_profit_unearned'	=>	'0.00',
                'tot_profit_earned'	=>	'95.84',
                'reporting_balance'	=>	NULL,
                'payment_amount'	=>	'262.50',
                'last_payment_date'	=>	'2021-06-09',
                'instalment_no'	=>	'2',
                'last_instalment_no'	=>	NULL,
                'instal_arrears_flag'	=>	NULL,
                'month_arrears'	=>	'0',
                'instal_arrears'	=>	'0.00',
                'fees_arrears'	=>	NULL,
                'credit_status'	=>	NULL,
                'credit_status_chgdate'	=>	NULL,
                'last_pymt_amt'	=>	'131.25',
                'instal_due_date'	=>	'2021-06-30',
                'last_instal_date'	=>	'2021-06-30',
                'last_instal_due_date'	=>	'2021-06-30',
                'part_instal_total'	=>	NULL,
                'income_in_suspense'	=>	NULL,
                'income_this_month'	=>	NULL,
                'income_arrears'	=>	NULL,
                'npf_status'	=>	'N',
                'npf_changed_date'	=>	NULL,
                'npf_provision'	=>	NULL,
                'first_npf_date'	=>	NULL,
                'mth_ageing'	=>	NULL,
                'sum_npf_provision'	=>	NULL,
                'recovered_amount'	=>	NULL,
                'service_charges'	=>	NULL,
                'unpaid_profit'	=>	NULL,
                'rebate_amount'	=>	NULL,
                'part_payoff_date'	=>	NULL,
                'full_release_flag'	=>	NULL,
                'lastbatchprocdt'	=>	NULL,
                'num_rescheduled'	=>	NULL,
                'resched_no'	=>	NULL,
                'verified_status'	=>	NULL,
                'verified_date'	=>	NULL,
                'last_modified_date'	=>	'2020-09-08',
                'last_modified_user'	=>	'dbo',
                'mbr_id'	=>	'4642.00',
                'fees_outs'	=>	'-60.00',
                'princp_collected'	=>	'166.66',
                'fees_collected'	=>	'60.00',
                'share_amt'	=>	NULL,
                'sinking_fund'	=>	'0.00',
                'bpa_collected'	=>	NULL,
                'early_rebate'	=>	NULL,
                'advance_payment'	=>	'0.00',
            ];
        }else{
            $this->account_position = [
                'actid'	=>	'169294',
                'account_no'	=>	'1001026203',
                'report_date'	=>	NULL,
                'cif_system'	=>	'A11',
                'undrawn_amount'	=>	'88000.00',
                'disbursed_amount'	=>	NULL,
                'bal_outstanding'	=>	'112578.40',
                'cost_outstanding'	=>	'88000.00',
                'prin_outstanding'	=>	'88000.00',
                'uei_outstanding'	=>	'0.00',
                'total_fees_amount'	=>	NULL,
                'tot_profit_unearned'	=>	'0.00',
                'tot_profit_earned'	=>	NULL,
                'reporting_balance'	=>	NULL,
                'payment_amount'	=>	NULL,
                'last_payment_date'	=>	NULL,
                'instalment_no'	=>	NULL,
                'last_instalment_no'	=>	NULL,
                'instal_arrears_flag'	=>	NULL,
                'month_arrears'	=>	NULL,
                'instal_arrears'	=>	NULL,
                'fees_arrears'	=>	NULL,
                'credit_status'	=>	'0.00',
                'credit_status_chgdate'	=>	NULL,
                'last_pymt_amt'	=>	NULL,
                'instal_due_date'	=>	NULL,
                'last_instal_date'	=>	NULL,
                'last_instal_due_date'	=>	NULL,
                'part_instal_total'	=>	NULL,
                'income_in_suspense'	=>	NULL,
                'income_this_month'	=>	NULL,
                'income_arrears'	=>	NULL,
                'npf_status'	=>	'N',
                'npf_changed_date'	=>	NULL,
                'npf_provision'	=>	NULL,
                'first_npf_date'	=>	NULL,
                'mth_ageing'	=>	NULL,
                'sum_npf_provision'	=>	NULL,
                'recovered_amount'	=>	NULL,
                'service_charges'	=>	NULL,
                'unpaid_profit'	=>	NULL,
                'rebate_amount'	=>	NULL,
                'part_payoff_date'	=>	NULL,
                'full_release_flag'	=>	NULL,
                'lastbatchprocdt'	=>	NULL,
                'num_rescheduled'	=>	NULL,
                'resched_no'	=>	NULL,
                'verified_status'	=>	NULL,
                'verified_date'	=>	NULL,
                'last_modified_date'	=>	'2021-04-09',
                'last_modified_user'	=>	'dbo',
                'mbr_id'	=>	'4642.00',
                'fees_outs'	=>	'0.00',
                'princp_collected'	=>	NULL,
                'fees_collected'	=>	NULL,
                'share_amt'	=>	NULL,
                'sinking_fund'	=>	NULL,
                'bpa_collected'	=>	NULL,
                'early_rebate'	=>	NULL,
                'advance_payment'	=>	NULL
            ];
        }
        return view('livewire.page.siskop.finance.position');
    }
}
